<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net6.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <ApplicationIcon>Synorvia_icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Data\**" />
      <Content Remove="Data\**" />
      <EmbeddedResource Remove="Data\**" />
      <None Remove="Data\**" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Program.cs" />
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" Version="6.0.553" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\MDD4All.Configuration\src\MDD4All.Configuration\MDD4All.Configuration-dev.csproj" />
      <ProjectReference Include="..\..\MDD4All.DME.AssemblyTree\src\MDD4All.DME.AssemblyTree\MDD4All.DME.AssemblyTree-dev.csproj" />
      <ProjectReference Include="..\..\MDD4All.DME.DataAccess\MDD4All.DME.DataAccess-dev.csproj" />
      <ProjectReference Include="..\..\MDD4All.FileAccess.WPF\src\MDD4All.FileAccess.WPF\MDD4All.FileAccess.WPF-dev.csproj" />
      <ProjectReference Include="..\..\MDD4All.UI.BlazorComponents\src\MDD4All.UI.BlazorComponents\MDD4All.UI.BlazorComponents-dev.csproj" />
      <ProjectReference Include="..\..\MDD4All.UI.DataModels\src\MDD4All.UI.DataModels\MDD4All.UI.DataModels-dev.csproj" />
      <ProjectReference Include="..\MDD4All.DME.DataModels\MDD4All.DME.ViewModels.Editor.csproj" />
      <ProjectReference Include="..\MDD4All.DME.Services\MDD4All.DME.Services.csproj" />
      <ProjectReference Include="..\MDD4All.DME.ViewModels.DataManger\MDD4All.DME.ViewModels.DataManager.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DataAccess\" />
      <Folder Include="wwwroot\css\bootstrap-icons\" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Program.cs" />
    </ItemGroup>

    <ItemGroup>
      <Page Include="App.xaml" />
    </ItemGroup>

</Project>
